version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    assignees:
      - "dearealeo"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps(ci)"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    assignees:
      - "dearealeo"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps"
    groups:
      production-deps:
        applies-to: version-updates
        dependency-type: production
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      development-deps:
        applies-to: version-updates
        dependency-type: development
        patterns:
          - "*"
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
