version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    assignees:
      - "dearealeo"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(ci)"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    assignees:
      - "dearealeo"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
