export const SITE = {
  website: "https://dearealeo.github.io",
  author: "dearealeo",
  profile: "",
  desc: "",
  title: "宋彥筠",
  ogImage: "",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: true,
    text: "Suggest Changes",
    url: "https://github.com/dearealeo/dearealeo.github.io/edit/main/",
  },
  dynamicOgImage: false,
  lang: "en",
  timezone: "Asia/Shanghai",
} as const;
